version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: me3co_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    networks:
      - me3co_network

networks:
  me3co_network:
    driver: bridge